# Generated by Django 3.1.1 on 2020-09-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='descriptino',
            new_name='description',
        ),
    ]
